# Generated by Django 6.0.4 on 2026-04-10 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_checkin_amount_paid_remove_checkin_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Incident',
        ),
    ]
