# Generated by Django 6.0.4 on 2026-04-14 11:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_room_price_per_night'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='chategory',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
