# Generated by Django 6.0.4 on 2026-04-16 18:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_room_chategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='check_in_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='check_out_date',
            field=models.DateTimeField(),
        ),
    ]
