# Generated by Django 6.0.4 on 2026-04-19 12:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_checkin_check_in_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Tekshirilmoqda'), ('verified', "Tasdiqlandi (O'g'rilik emas)"), ('theft', "O'g'rilik aniqlandi")], default='pending', max_length=20)),
                ('video_clip', models.FileField(blank=True, null=True, upload_to='security_alerts/')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.room')),
            ],
        ),
    ]
