# Generated by Django 6.0.4 on 2026-04-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_securityalert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='securityalert',
            options={'ordering': ['-detected_at'], 'verbose_name': 'Xavfsizlik Ogohlantirishi', 'verbose_name_plural': 'Xavfsizlik Ogohlantirishlari'},
        ),
        migrations.RemoveField(
            model_name='securityalert',
            name='room',
        ),
        migrations.AlterField(
            model_name='securityalert',
            name='status',
            field=models.CharField(choices=[('pending', 'Tekshirilmoqda'), ('verified', 'Tasdiqlandi'), ('theft', "O'g'rilik aniqlandi")], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='securityalert',
            name='video_clip',
            field=models.FileField(blank=True, null=True, upload_to='security_alerts/%Y/%m/%d/'),
        ),
    ]
