# Generated by Django 6.0.4 on 2026-05-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_profile_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='note',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Tarjimai hol'),
        ),
    ]
