# Generated by Django 6.0.4 on 2026-05-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_profile_options_remove_profile_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('zone_type', models.CharField(choices=[('cashier', 'Kassa hududi'), ('entry', 'Kirish eshigi'), ('corridor', "Yo'lak"), ('storage', 'Omborxona')], max_length=20)),
                ('coordinates', models.JSONField(help_text='Zonaning nuqtalar koordinatalari')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kamera Zonasi',
                'verbose_name_plural': 'Kamera zonalari',
            },
        ),
    ]
