# Generated by Django 6.0.4 on 2026-05-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_camerazone'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='tuya_device_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
