# Generated by Django 6.0.4 on 2026-05-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_securityalert_alert_type_securityalert_risk_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='door_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='door_status',
            field=models.CharField(default='closed', max_length=10),
        ),
    ]
