# Generated by Django 6.0.4 on 2026-05-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_room_door_last_updated_room_door_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='size_room',
            field=models.PositiveIntegerField(default=25, help_text='Xona hajmi (m²)'),
        ),
    ]
